import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { AiOutlineLoading } from "react-icons/ai";
import Head from "next/head";
import LingkaranAbsen from "../../components/LingkaranAbsen";

export default function Presensi({ token }) {
  const router = useRouter;
  const redirect = (e) => {
    e.preventDefault();

    router.push("/auth");
  };

  return (
    <div className="">
      <Head>
        <title>TEC Internship 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets_intern/logo.png" />
      </Head>
      <main className="flex h-screen w-screen justify-center max-h-screen relative md:bg-[url('../public/assets_intern/bg-texture1.png')] bg-no-repeat bg-cover bg-center bg-fixed">
        <div className="absolute left-2 top-2 p-8 md:px-16 md:py-10 z-10">
          <div className="flex gap-2 cursor-pointer">
            <Link href={"/"}>
              <Image
                className=""
                src="/assets_intern/logo.png"
                width={65}
                height={65}
                alt="logo"
              />
            </Link>
          </div>
        </div>
        {token ? (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 xl:gap-x-[100px] 2xl:gap-x-[150px] gap-y-[50px] items-center mb-20 mt-20 mx-10">
            <LingkaranAbsen active={false} day={1} />
            <LingkaranAbsen active={false} day={2} />
            <LingkaranAbsen
              active={true}
              day={3}
              link={"https://bit.ly/PresensiAwalTECademyDay3"}
            />
          </div>
        ) : (
          <>
            <div className="flex items-center justify-center h-full">
              <AiOutlineLoading className="animate-spin" />
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}
