import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { AiOutlineLoading } from "react-icons/ai";
import Head from "next/head";
import LingkaranAbsen from "../../components/LingkaranAbsen";
import Navbar from "../../components/Navbar";
import { useState, useEffect } from "react";

export default function Presensi({ token }) {
  const router = useRouter;
  const [expiryTime, setExpiryTime] = useState("23 Oct 2022 12:40:50");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const timeInterval = setInterval(() => {
      const countdownDateTime = new Date(expiryTime).getTime();
      const currentTime = new Date().getTime();
      const remainingDayTime = countdownDateTime - currentTime;

      if (remainingDayTime < 0) {
        clearInterval(timeInterval);
        setExpiryTime(false);
      }
    }, 1000);

    return () => {
      clearInterval(timeInterval);
    };
  });

  useEffect(() => {
    setTimeout(() => {
      setLoaded(true);
    }, 1500);
  }, []);

  const redirect = (e) => {
    e.preventDefault();

    router.push("/auth");
  };

  return (
    <div className="px-8 md:px-16 md:py-10 lg:px-20">
      <Head>
        <title>TEC Internship 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets_intern/logo.png" />
      </Head>
      <main className="flex flex-col items-center min-h-screen">
        <Navbar token={token} />
        <div className=" absolute right-0 top-0 opacity-50 flex -z-50 sm:w-[400px] md:w-[600px]">
          <img className="" src="/assets_intern/perisai-kanan.png" alt=""></img>
        </div>
        <div className="text-5xl mt-36 text-center">PRESENSI DAY</div>
        <div className="min-h-screen flex items-center">
          {token && loaded ? (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 xl:gap-x-[100px] 2xl:gap-x-[150px] gap-y-[50px] items-center mb-20 mt-20 mx-10">
              <LingkaranAbsen active={false} day={1} />
              <LingkaranAbsen active={false} day={2} />
              <LingkaranAbsen active={false} day={3} />
              <LingkaranAbsen active={false} day={4} />
              <LingkaranAbsen active={false} day={5} />
              <LingkaranAbsen
                active={true}
                day={6}
                link={"https://bit.ly/PresensiAwalDay6TECademy"}
              />
            </div>
          ) : (
            <>
              <div className="flex items-center justify-center h-full">
                <AiOutlineLoading className="animate-spin" />
              </div>
            </>
          )}
        </div>
      </main>
    </div>
  );
}

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}
