import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TEC Internship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <Navbar />

      <main>
        <div className="flex justify-center items-center mt-24 space-x-24 font-bold">
          <Image
            className=""
            src="/logo.png"
            width={500}
            height={500}
            layout="fixed"
            alt="asa"
          />
          <div className="space-y-6 self-center">
            <h1 className="text-7xl">Welcome to TEC Internship</h1>
            <button className="bg-gradient-to-br from-[#9ADFD3] to-[#2F9685] rounded-md px-6 py-3 text-2xl border">
              Join Us!
            </button>
          </div>
        </div>

        <section className="px-8 mt-20">
          <h1 className="font-bold text-5xl mb-5">TEC Internship</h1>
          <p
            className="text-2xl px-3 py-5 justify-center 
        relative z-10 bg-gradient bg-gradient-to-br from-gray-300 to-transparent 
        bg-opacity-20 rounded-md shadow-md card border"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
            fermentum ex nibh, sed varius turpis pellentesque viverra. Praesent
            sollicitudin finibus odio, nec aliquet nunc sagittis sed. Mauris
            venenatis ante et dolor facilisis, vel sagittis metus vulputate.
            Pellentesque at fermentum purus. Donec rhoncus lectus nec leo
            imperdiet consequat.
          </p>
        </section>
      </main>

      <footer className={styles.footer}>
        <p>TEC Internship 2022 </p>
      </footer>
    </div>
  );
}
